#!/bin/sh

# Setup passwordless commands
echo 'alex ALL=(ALL) NOPASSWD: /usr/bin/pacman, /usr/bin/paru, /usr/bin/systemctl' | sudo tee /etc/sudoers.d/alex

# Install Git (needed for paru)
sudo pacman -S git

# Install paru
git clone https://aur.archlinux.org/paru.git /tmp/paru
cd /tmp/paru
makepkg -si

# Intall other packages
paru -S 1password adobe-source-han-sans-otc-fonts adobe-source-han-serif-otc-fonts alacritty amd-ucode anki arandr bat cups deluge-gtk dmenu dosfstools dunst exa feh firefox fzf gnome-keyring gnumeric i3-wm i3blocks maim man-db mumble neovim ntfs-3g pamixer pass pulsemixer ripgrep rofi rofi-pass rsync signal-desktop slock starship steam telegram-desktop thunderbird ttf-joypixels ttf-liberation unclutter unzip zip zoxide zsh

# Set up dotfiles
git clone "https://github.com/hildebro/dotfiles" /tmp/dotfiles
cp -rfT /tmp/dotfiles /home/alex
mv /home/alex/.git /home/alex/.dotfiles

# Change shell to zsh
chsh -s $(which zsh)

# Remove bash* files from home directory
find /home/alex -name 'bash*' -type f -delete

# Setup reflector for pacman mirrorlist
sudo pacman -S reflector
sudo reflector --country 'Germany' --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
sudo systemctl enable --now reflector.timer

# Setup X11 gpu config
cat <<EOF | sudo tee /etc/X11/xorg.conf.d/20-amdgpu.conf
Section "Device"
   Identifier "AMD"
   Driver "amdgpu"
   Option "VariableRefresh" "true"
   Option "TearFree" "true"
EndSection
EOF

# Setup docker
sudo pacman -S docker docker-compose
sudo usermod -aG docker alex
sudo systemctl enable --now docker.service

# Setup hostname resolution
sudo pacman -S avahi nss-mdns
sudo systemctl enable --now avahi-daemon.service

# Setup greetd
sudo pacman -S greetd greetd-tuigreet xorg-server xorg-xinit
cat <<EOF | sudo tee /etc/greetd/config.toml
[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# $(agreety) is the bundled agetty/login-lookalike. You can replace $(/bin/sh)
# with whatever you want started, such as $(sway).
command = "tuigreet --cmd startx"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the $(video) group.
user = "greeter"
EOF
sudo systemctl enable --now greetd.service

# cleanup vim and zsh configs
# init gpg
# enable multilib
