#!/bin/sh

# Setup passwordless commands
echo 'alex ALL=(ALL) NOPASSWD: /usr/bin/pacman, /usr/bin/paru, /usr/bin/systemctl' | sudo tee /etc/sudoers.d/alex
sudo usermod -aG video alex
sudo usermod -aG games alex
sudo usermod -aG audio alex
sudo usermod -aG wheel alex

# Install Git (needed for paru)
sudo pacman -S git

# Install paru
git clone https://aur.archlinux.org/paru.git /tmp/paru
cd /tmp/paru
makepkg -si

# Intall other packages
paru -S 1password alacritty amd-ucode ansible ansible-core bat btop cups deluge-gtk dunst exa firefox fzf gamemode gnome-keyring gnumeric grim htop hyprland hyprpolkitagent-git intellij-idea-ultimate-edition intellij-idea-ultimate-edition-jre man-db mumble nemo neovim noto-fonts-cjk otf-comicshanns-nerd otf-font-awesome pipewire pipewire-alsa pipewire-pulse lib32-pipewire pulsemixer ripgrep rsync signal-desktop slurp starship steam telegram-desktop thunderbird ttf-nerd-fonts-symbols unzip uwsm wireplumber wl-clipboard zathura zip zoxide zsh

# In case archinstall doesn't cover everythings
paru -S lib32-vulkan-radeon vulkan-radeon xf86-video-amdgpu

# Set up dotfiles
git clone "https://github.com/hildebro/dotfiles" /tmp/dotfiles
cp -rfT /tmp/dotfiles /home/alex
mv /home/alex/.git /home/alex/.dotfiles

# Change shell to zsh
chsh -s $(which zsh)

# Setup reflector for pacman mirrorlist
sudo pacman -S reflector
sudo reflector --country 'Germany' --latest 5 --protocol https --save /etc/pacman.d/mirrorlist
sudo systemctl enable --now reflector.timer

# Setup docker
sudo pacman -S docker docker-compose
sudo usermod -aG docker alex
sudo systemctl enable --now docker.service

# Setup hostname resolution
sudo pacman -S avahi nss-mdns
sudo systemctl enable --now avahi-daemon.service

# Setup greetd
sudo pacman -S greetd greetd-tuigreet
cat <<EOF | sudo tee /etc/greetd/config.toml
[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
command = "tuigreet --asterisks --remember --remember-session --time"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
EOF
sudo systemctl enable --now greetd.service

## Enable bluetooth
#paru -S bluez bluez-manager
#sudo systemctl enable --now bluetooth

# backlight control
# sudo usermod -aG video alex
# udev rules.d backlight.rules
# ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video $sys$devpath/brightness", RUN+="/bin/chmod g+w $sys$devpath/brightness"

####### TODO turn into commands

# change dotfile remote url to `git` path instead of `https`

####### Manual after logging into the clean state

# Remove .bash files from home directory

# Copy gpg config from old machine

# Firefox: Force fullscreen to stay inside the window
# Type about:config in the address bar, then search for "full-screen-api.ignore-widgets" Set that to true.

