directory: /srv/files/Music/
library: /home/alex/.local/share/musiclibrary.db

plugins:
  - info
  - musicbrainz
  - genre_tree

musicbrainz:
  genres: yes

import:
  copy: no
  move: no

pluginpath:
  - ~/.config/beets/beetsplug

