[telegram]
api_key = "933449501:AAEDWYnZmAAf1OcTkb_CqOTDEg0asYhSqu4"
worker_count = 5
admin = "hildebro"
admin_id = 123018278

[database]
sql_uri = "sqlite:///hetznerbot.db"

[logging]
sentry_enabled = false
sentry_token = ""

[webhook]
enabled = false
domain = "https://localhost"
token = "hetznerbot"
cert_path = "/path/to/cert.pem"
port = 7000
