#!/bin/sh

command=$BLOCK_NAME
separator_block_width=30
markup=pango

#[music]
#label=🎼
#interval=once
#signal=11

#[pacpackages]
#label=📦
#interval=once
#signal=8

#[torrent]
#interval=20
#signal=7

#[weather]
#interval=18000
#signal=5

#[mailbox]
#label=📬
#interval=180
#signal=12

[volume]
interval=60
signal=10

[cpu_stats]
interval=10

#[gpu_stats]
#interval=10

[disk]
interval=60
command=disk / Root

#[iplocate]
#interval=60

[internet]
interval=10

[battery]
command=battery BAT0
interval=5

[clock]
interval=30

